# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Austin's website
email: austin.j.lippert@gmail.com #I'm making the assumption that your-email@example.com is my personal email
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  #I'm making the assumption that baseurl and url are both my website's url. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://austin.wannabedev.net" # the base hostname & protocol for your site, e.g. http://example.com
#Commenting out lines 30-31 because I don't think I need them
#twitter_username: jekyllrb 
#github_username:  jekyll

# Build settings
theme: jekyll-theme-console
plugins:
#jekyll-feed was the only plugin here prior to my edit
  - bundler
  - rake
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  #- jekyll-theme-console

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
