theme: 'jekyll-theme-developer', '~> 0.4.2'
bundle exec jekyll serve

# Site settings
title: Austin Lippert
#email: command was here

include: ["index.html"]
exclude: ["Gemfile"]

#write html inside the double quotes to display in jumbotron
#AUSTIN'S COMMENT: I don't know what this is yet
#description: "<h3>Hello, world!</h3><h1>DevJournal</h1><h3>Awesome Jekyll Theme for Developers!</h3>Hope you like it!"

#plugins
plugins:
  - bundler
  - rake
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-theme-developer

#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://austin.wannabedev.net" # the base hostname & protocol for your site
#I don't want to display my account info yet, would like to have everything in order first 
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings, Austin: I also don't know what this is yet, I assume my design.md file
markdown: design.md
