source 'https://rubygems.org'

bundle exec jekyll serve
gem 'jekyll', '~> 4.0', '>= 4.0.1'

group :jekyll_plugins do  
  gem 'bundler', '~> 2.1', '>= 2.1.4'
  gem 'rake', '~> 13.0', '>= 13.0.1'
  gem 'jekyll-feed', '~> 0.13.0'
  gem 'jekyll-gist', '~> 1.5'
  gem 'jekyll-paginate', '~> 1.1'
  gem 'jekyll-seo-tag', '~> 2.6', '>= 2.6.1'
  gem 'jekyll-sitemap', '~> 1.4'
  gem 'jekyll-theme-developer', '~> 0.4.2'
end

bundle update
