name: Seaborn-pandas CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
              
      - name: "Build Jekyll"
        run: "jekyll build" 
      - name: "Build image"
      - run:  "run: docker build -t 5348094/public:latest ."  
      - name: Build the Docker image
        uses: docker/build-push-action@v1
        
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: 5348094/_site
          tags: latest
        
